[package]
name = "openid-client"
version = "0.0.11-dev"
edition = "2021"
license = "MIT"
description = "Work In Progress OpenId Connect Client"
homepage = "https://github.com/sathyajithps/openid-client"
repository = "https://github.com/sathyajithps/openid-client"
documentation = "https://docs.rs/openid-client"
readme = "README.md"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "native-tls"] }
httpmock = "0.6.7"
url = "2.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
lazy_static = "1.4.0"
tokio = { version = "1.26.0", features = ["full"] }
rsa = "0.9.2"
rand = "0.8.5"
base64 = "0.21.0"
uuid = {version = "1.3.0", features = ["v4"]}

[lib]
doctest = false