[package]
name = "openid-client"
version = "0.0.25-dev"
edition = "2021"
license = "MIT"
description = "Work In Progress OpenId Connect Client"
homepage = "https://github.com/sathyajithps/openid-client"
repository = "https://github.com/sathyajithps/openid-client"
documentation = "https://docs.rs/openid-client"
readme = "README.md"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "native-tls"] }
httpmock = "0.6.8"
url = "2.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["full"] }
josekit = { git = "https://github.com/sathyajithps/josekit-rs.git" }
assert-json-diff = "2.0.2"
base64-url = "2.0.0"
sha2 = "0.10.7"
urlencoding = "2.1.3"
base64 = "0.21.2"
rand = "0.8.5"
lazy_static = "1.4.0"
regex = "1.9.3"

[lib]
doctest = false
