[package]
name = "openid-client"
version = "0.0.1-dev"
edition = "2021"
license = "MIT"
description = "Working on an Open Id Connect Client for rust.Will update."
homepage = "https://openid.net/"
repository= "https://github.com/sathyajithps/openid-client"
documentation = "https://openid.net/connect/"
readme= "README.md"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "native-tls"] }
httpmock = "0.6.7"
url = "2.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
lazy_static = "1.4.0"
