[book]
authors = ["Sathyajith P S"]
language = "en"
multilingual = false
src = "src"
title = "OpenId Client"
description = "This is the documentation for the openid-client crate for rust."

[output.html.playground]
runnable = false
[output.html]
default-theme = "coal"
git-repository-url = "https://github.com/sathyajithps/openid-client"