name: Publish to crates.io

on:
    pull_request:
        branches:
            - master
        types: [closed]

jobs:
    publish:
        if: ${{ github.event.pull_request.merged }}
        continue-on-error: false
        name: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3

            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Running Tests
              run: cargo test -- --include-ignored

            - name: Publishing
              run: cargo publish --token ${CRATES_TOKEN}
              env:
                  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
